### ISSUE TITLE
Brick integration

### ISSUE THREAD

**Issue by aviveiros11** [NatLabRockies/tasty#20]
Create and define Tasty Templates for the Brick Schema - may be expanded into multiple issues.  

---

- [ ] data graph
   - incorporate https://github.com/gtfierro/oomason
- [ ] shapes graph (from Brick)
   - automate `generated_shapes/brick_all.ttl`
- [x] (in)validation examples
   - #58

**Comment by MatthewSteen** [comment]
Shapes were added after the 1.2.0 release, see...

- https://github.com/BrickSchema/Brick/pull/285
- https://docs.brickschema.org/lifecycle/validation.html

**Comment by MatthewSteen** [comment]
https://github.com/NREL/BuildingMOTIF/pull/70
