### ISSUE TITLE
Point level validation

### ISSUE THREAD

**Issue by aviveiros11** [NatLabRockies/tasty#25]
Confirm validation for all point level first-class entity types

**Comment by MatthewSteen** [comment]
Could include Haystack [protos](https://project-haystack.org/doc/proto/index).

![image](https://user-images.githubusercontent.com/8397034/123491007-de0a5680-d5d2-11eb-9e78-736aa98bb285.png)

**Comment by MatthewSteen** [comment]
https://github.com/NREL/BuildingMOTIF/pull/92
