### ISSUE TITLE
rethink API classes / functions

### ISSUE THREAD

**Issue by corymosiman12** [NatLabRockies/tasty#8]

**Comment by corymosiman12** [comment]
initial stab here: https://github.com/NREL/tasty/pull/9

**Comment by MatthewSteen** [comment]
Some ideas...

### Structure
```text
tasty/
|--schemas/
|  |--brick_v1.ttl
|  |--haystack_v1.ttl
|  |--s223_v1.ttl
|--scripts (utils)/
   |--some_script.py
|--shapes/
   |--shape_graphs (generated_shapes)/
   |  |--haystack.ttl
   |  |--brick.ttl
   |  |--s223.ttl
   |--haystack.json
   |--brick.json
   |--s223.json
|--console.py
|--constants.py
|--entities.py
|--exceptions.py
|--graphs.py
|--shapes.py
|--templates.py
|--validate.py
|--...
```

### Directories
1. Combine `generated_shapes/` and `source_shapes/` directories into a new `shapes/` directory with subdirectories.

### Files
#### `entities.py`
2. Move `Shape` classes to new `shapes.py` module. 
   - SimpleShape
   - CompositeShape
   - ShapesWrapper
3. Move schema-specific classes to separate file/module for each schema.
    - `brick.py`
    - `haystack.py`
    - `s223.py`

#### `graphs.py`
4. `bind_prefixes` => `bind_common_prefixes`
5. `bind_versioned_prefixes` => `bind_schema_prefixes`
   - Consider moving prefix strings to `constants.py` data structure.
   - ...___OR__ merge the two functions into a single `bind_prefixes` function._

#### `shapes_*.py`
6. Combine `shapes_loader.py`, which has a single method, with `shapes_generator.py` and rename `shapes.py`.
 
#### `validate.py`
7. Add wrappers for pyshacl like [BrickSchema/py-brickschema/brickschema/validate.py](https://github.com/BrickSchema/py-brickschema/blob/master/brickschema/validate.py).
